-- ANALISE DE ACESSOS DO SITE
-- Rode este arquivo no SQL Editor do Supabase.
-- Ele cria a tabela que recebe os eventos do site e um usuario admin para ver o painel.

create table if not exists public.analytics_eventos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  username text,
  plano text,
  sessao_id text,
  ip text,
  evento text not null,
  alvo_tipo text,
  alvo_titulo text,
  alvo_url text,
  pagina text,
  user_agent text,
  detalhes jsonb not null default '{}'::jsonb
);

alter table public.analytics_eventos
add column if not exists created_at timestamptz not null default now();

alter table public.analytics_eventos
add column if not exists username text;

alter table public.analytics_eventos
add column if not exists plano text;

alter table public.analytics_eventos
add column if not exists sessao_id text;

alter table public.analytics_eventos
add column if not exists ip text;

alter table public.analytics_eventos
add column if not exists evento text;

alter table public.analytics_eventos
add column if not exists alvo_tipo text;

alter table public.analytics_eventos
add column if not exists alvo_titulo text;

alter table public.analytics_eventos
add column if not exists alvo_url text;

alter table public.analytics_eventos
add column if not exists pagina text;

alter table public.analytics_eventos
add column if not exists user_agent text;

alter table public.analytics_eventos
add column if not exists detalhes jsonb not null default '{}'::jsonb;

alter table public.analytics_eventos enable row level security;

drop policy if exists "analytics_insert_todos" on public.analytics_eventos;
create policy "analytics_insert_todos"
on public.analytics_eventos
for insert
to anon, authenticated
with check (
  evento is not null
  and length(trim(evento)) > 0
);

drop policy if exists "analytics_select_todos" on public.analytics_eventos;
create policy "analytics_select_todos"
on public.analytics_eventos
for select
to anon, authenticated
using (true);

create index if not exists analytics_eventos_created_idx
on public.analytics_eventos (created_at desc);

create index if not exists analytics_eventos_plano_evento_idx
on public.analytics_eventos (plano, evento, created_at desc);

create index if not exists analytics_eventos_ip_idx
on public.analytics_eventos (ip, created_at desc);

create index if not exists analytics_eventos_sessao_idx
on public.analytics_eventos (sessao_id, created_at desc);

-- Usuario para abrir a pagina analytics.html.
-- Depois de testar, pode trocar a senha direto na tabela usuarios.
insert into public.usuarios (
  username,
  senha,
  ativo,
  plano,
  expira_em
)
values (
  'admin',
  'admin123',
  true,
  'admin',
  null
)
on conflict (username) do update
set
  senha = excluded.senha,
  ativo = true,
  plano = 'admin',
  expira_em = null,
  atualizado_em = now();

-- Ver resumo rapido:
-- select plano, evento, count(*) as total
-- from public.analytics_eventos
-- group by plano, evento
-- order by total desc;

-- Ver jornada de um IP:
-- select created_at at time zone 'America/Sao_Paulo' as horario_brasil, username, plano, evento, alvo_titulo
-- from public.analytics_eventos
-- where ip = 'COLOQUE_O_IP_AQUI'
-- order by created_at asc;
