-- Configuracao da tabela de comentarios.
-- Rode no SQL Editor do Supabase se os comentarios nao aparecerem ou nao enviarem pelo site.

create table if not exists public.comentarios (
  id bigint generated by default as identity primary key,
  username text not null,
  texto text not null,
  created_at timestamptz not null default now()
);

alter table public.comentarios
add column if not exists created_at timestamptz not null default now();

alter table public.comentarios enable row level security;

drop policy if exists "comentarios_select_todos" on public.comentarios;
create policy "comentarios_select_todos"
on public.comentarios
for select
to anon, authenticated
using (true);

drop policy if exists "comentarios_insert_todos" on public.comentarios;
create policy "comentarios_insert_todos"
on public.comentarios
for insert
to anon, authenticated
with check (
  length(trim(username)) > 0
  and length(trim(texto)) > 0
);

-- Conferir comentarios:
-- select username, texto, created_at
-- from public.comentarios
-- order by created_at desc;
