-- Modo de previa para o usuario teste / 123.
-- Rode este arquivo no SQL Editor do Supabase.

create table if not exists public.vip_config (
  id bigint generated by default as identity primary key,
  ativo boolean not null default true,
  contato_nome text not null default 'Amanda',
  telegram_url text,
  whatsapp_url text,
  botao_contato_texto text not null default 'Chamar no WhatsApp',
  mensagem_video text not null default 'Entre em contato com {contato} para assinar o VIP e continuar assistindo.',
  mensagem_foto text not null default 'Para ver todas as fotos sem censura, assine o VIP com {contato}.',
  preview_segundos integer not null default 5,
  chamada_previa_video_url text,
  chamada_previa_duracao integer,
  updated_at timestamptz not null default now()
);

create table if not exists public.fotos_previas (
  id bigint generated by default as identity primary key,
  ativo boolean not null default true,
  ordem integer not null default 0,
  titulo text not null default 'Previa',
  imagem_url text not null,
  thumb_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.vip_ofertas (
  id bigint generated by default as identity primary key,
  ativo boolean not null default true,
  ordem integer not null default 0,
  categoria text not null default 'vip',
  titulo text not null,
  descricao text,
  valor text not null,
  destaque boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comentarios (
  id bigint generated by default as identity primary key,
  username text not null,
  texto text not null,
  created_at timestamptz not null default now()
);

alter table public.comentarios
add column if not exists created_at timestamptz not null default now();

alter table public.vip_config enable row level security;
alter table public.fotos_previas enable row level security;
alter table public.vip_ofertas enable row level security;
alter table public.comentarios enable row level security;

alter table public.vip_config
add column if not exists whatsapp_url text;

alter table public.vip_config
add column if not exists botao_contato_texto text not null default 'Chamar no WhatsApp';

alter table public.vip_config
add column if not exists chamada_previa_video_url text;

alter table public.vip_config
add column if not exists chamada_previa_duracao integer;

alter table public.vip_config
alter column chamada_previa_duracao drop not null;

alter table public.vip_config
alter column chamada_previa_duracao drop default;

alter table public.usuarios
add column if not exists ativo boolean not null default true;

alter table public.usuarios
add column if not exists plano text;

alter table public.usuarios
add column if not exists expira_em timestamptz;

alter table public.usuarios
add column if not exists criado_em timestamptz not null default now();

alter table public.usuarios
add column if not exists atualizado_em timestamptz not null default now();

create or replace function public.bloquear_usuarios_expirados()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.usuarios
  set
    ativo = false,
    atualizado_em = now()
  where ativo = true
    and expira_em is not null
    and expira_em <= now();
end;
$$;

grant execute on function public.bloquear_usuarios_expirados() to anon, authenticated;

create or replace function public.criar_ou_renovar_usuario(
  p_username text,
  p_senha text,
  p_plano text,
  p_dias integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.usuarios
  set
    senha = p_senha,
    ativo = true,
    plano = p_plano,
    expira_em = now() + make_interval(days => p_dias),
    atualizado_em = now()
  where username = p_username;

  if not found then
    insert into public.usuarios (
      username,
      senha,
      ativo,
      plano,
      expira_em,
      criado_em,
      atualizado_em
    )
    values (
      p_username,
      p_senha,
      true,
      p_plano,
      now() + make_interval(days => p_dias),
      now(),
      now()
    );
  end if;
end;
$$;

revoke execute on function public.criar_ou_renovar_usuario(text, text, text, integer) from public;

drop policy if exists "vip_config_select_ativos" on public.vip_config;
create policy "vip_config_select_ativos"
on public.vip_config
for select
to anon, authenticated
using (ativo = true);

drop policy if exists "fotos_previas_select_ativas" on public.fotos_previas;
create policy "fotos_previas_select_ativas"
on public.fotos_previas
for select
to anon, authenticated
using (ativo = true);

drop policy if exists "vip_ofertas_select_ativas" on public.vip_ofertas;
create policy "vip_ofertas_select_ativas"
on public.vip_ofertas
for select
to anon, authenticated
using (ativo = true);

drop policy if exists "comentarios_select_todos" on public.comentarios;
create policy "comentarios_select_todos"
on public.comentarios
for select
to anon, authenticated
using (true);

drop policy if exists "comentarios_insert_todos" on public.comentarios;
create policy "comentarios_insert_todos"
on public.comentarios
for insert
to anon, authenticated
with check (
  length(trim(username)) > 0
  and length(trim(texto)) > 0
);

insert into public.vip_config (
  ativo,
  contato_nome,
  telegram_url,
  whatsapp_url,
  botao_contato_texto,
  mensagem_video,
  mensagem_foto,
  preview_segundos,
  chamada_previa_video_url,
  chamada_previa_duracao
)
select
  true,
  'Amanda',
  '',
  '',
  'Chamar no WhatsApp',
  'Entre em contato com {contato} para assinar o VIP e continuar assistindo.',
  'Para ver todas as fotos sem censura, assine o VIP com {contato}.',
  5,
  '',
  null
where not exists (
  select 1 from public.vip_config
);

update public.vip_config
set
  preview_segundos = 5,
  chamada_previa_duracao = case
    when chamada_previa_duracao is not null and chamada_previa_duracao < 5 then null
    else chamada_previa_duracao
  end
where ativo = true
  and (
    preview_segundos > 5
    or chamada_previa_duracao is null
    or chamada_previa_duracao < 5
  );

update public.vip_config
set botao_contato_texto = 'Chamar no WhatsApp'
where ativo = true
  and (
    botao_contato_texto is null
    or botao_contato_texto = ''
    or botao_contato_texto ilike '%telegram%'
  );

insert into public.vip_ofertas (
  ordem,
  categoria,
  titulo,
  descricao,
  valor,
  destaque
)
select *
from (
  values
    (1, 'chamada', 'CHAMADA ATE GOZAR ❤️', 'MAXIMO 10mn', 'R$ 30,00', true),
    (2, 'chamada', 'CHAMADA 5 MINUTOS ❤️', null, 'R$ 20,00', false),
    (3, 'vip', '1 DIA DE ACESSO', null, 'R$ 10,00', false),
    (4, 'vip', 'SEMANAL 7 DIAS + VIP 🎁', null, 'R$ 15,00', true),
    (5, 'vip', 'MENSAL 30 DIAS + PREMIUM 🎁', null, 'R$ 20,00', true),
    (6, 'vip', '3 MESES DE ACESSO 🎁', null, 'R$ 50,00', false),
    (7, 'mimo', 'MANDA UM MIMO 🎁', 'Em troca de uma foto minha', 'R$ 5,00', false),
    (8, 'mimo', 'MANDA UM MIMO 🎁', 'Em troca de um video meu', 'R$ 10,00', false)
) as ofertas(ordem, categoria, titulo, descricao, valor, destaque)
where not exists (
  select 1 from public.vip_ofertas
);

update public.usuarios
set
  senha = '123',
  ativo = true,
  plano = 'teste',
  expira_em = null,
  atualizado_em = now()
where username = 'teste';

insert into public.usuarios (username, senha, ativo, plano, expira_em)
select 'teste', '123', true, 'teste', null
where not exists (
  select 1 from public.usuarios where username = 'teste'
);

update public.usuarios
set
  senha = '123',
  ativo = true,
  plano = 'teste',
  expira_em = null,
  atualizado_em = now()
where username = '123';

insert into public.usuarios (username, senha, ativo, plano, expira_em)
select '123', '123', true, 'teste', null
where not exists (
  select 1 from public.usuarios where username = '123'
);

-- Planos atuais:
-- 1 dia:  select public.criar_ou_renovar_usuario('cliente1', 'senha123', '1_dia', 1);
-- 7 dias: select public.criar_ou_renovar_usuario('cliente1', 'senha123', '7_dias', 7);
-- 30 dias: select public.criar_ou_renovar_usuario('cliente1', 'senha123', '30_dias', 30);
-- 3 meses: select public.criar_ou_renovar_usuario('cliente1', 'senha123', '3_meses', 90);

-- Para bloquear imediatamente todos os usuarios vencidos:
-- select public.bloquear_usuarios_expirados();

-- Para ver quem esta ativo e quando vence:
-- select username, plano, ativo, expira_em
-- from public.usuarios
-- order by expira_em nulls last;

-- Para cadastrar uma foto censurada de previa:
-- Agora basta preencher imagem_url. thumb_url pode ficar vazio.
-- Use preferencialmente um link publico do Cloudflare R2.
-- insert into public.fotos_previas (titulo, imagem_url, ordem)
-- values ('Previa 1', 'https://pub-seu-bucket.r2.dev/foto-censurada.jpg', 1);

-- Para cadastrar um video no R2:
-- insert into public.conteudo (tipo, titulo, stream_url, thumb_url)
-- values ('video', 'Video 1', 'https://pub-seu-bucket.r2.dev/video.mp4', null);

-- Para trocar o WhatsApp do botao:
-- update public.vip_config
-- set whatsapp_url = 'https://wa.me/5599999999999',
--     botao_contato_texto = 'Chamar no WhatsApp',
--     contato_nome = 'Amanda'
-- where ativo = true;
