-- SUPABASE GERAL DO PROJETO
-- Rode este arquivo no SQL Editor do Supabase.
-- Ele cria/atualiza todas as tabelas usadas pelo site atual:
-- usuarios, conteudo, comentarios, vip_config, vip_ofertas, fotos_previas,
-- analytics_eventos, chamadas_previas, chamada_mensagens e sala_status.

create extension if not exists pgcrypto;

-- =========================================================
-- TABELA: usuarios
-- Usada pelo login simples do site.
-- =========================================================

create table if not exists public.usuarios (
  username text primary key,
  senha text not null,
  ativo boolean not null default true,
  plano text,
  expira_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table public.usuarios
add column if not exists senha text;

alter table public.usuarios
add column if not exists ativo boolean not null default true;

alter table public.usuarios
add column if not exists plano text;

alter table public.usuarios
add column if not exists expira_em timestamptz;

alter table public.usuarios
add column if not exists criado_em timestamptz not null default now();

alter table public.usuarios
add column if not exists atualizado_em timestamptz not null default now();

-- O login atual consulta a tabela usuarios direto pelo anon key.
-- Por isso deixamos RLS desativado nesta tabela para nao quebrar o login simples.
alter table public.usuarios disable row level security;

-- =========================================================
-- TABELA: conteudo
-- Guarda videos e fotos do VIP.
-- tipo: video ou foto
-- stream_url: link principal do video/foto
-- thumb_url: miniatura opcional
-- =========================================================

create table if not exists public.conteudo (
  id bigint generated by default as identity primary key,
  tipo text not null,
  titulo text not null,
  stream_url text not null,
  thumb_url text,
  created_at timestamptz not null default now()
);

alter table public.conteudo
add column if not exists tipo text;

alter table public.conteudo
add column if not exists titulo text;

alter table public.conteudo
add column if not exists stream_url text;

alter table public.conteudo
add column if not exists thumb_url text;

alter table public.conteudo
add column if not exists created_at timestamptz not null default now();

alter table public.conteudo enable row level security;

drop policy if exists "conteudo_select_todos" on public.conteudo;
create policy "conteudo_select_todos"
on public.conteudo
for select
to anon, authenticated
using (true);

-- =========================================================
-- TABELA: comentarios
-- Comentarios exibidos para todos os usuarios.
-- =========================================================

create table if not exists public.comentarios (
  id bigint generated by default as identity primary key,
  username text not null,
  texto text not null,
  created_at timestamptz not null default now()
);

alter table public.comentarios
add column if not exists username text;

alter table public.comentarios
add column if not exists texto text;

alter table public.comentarios
add column if not exists created_at timestamptz not null default now();

alter table public.comentarios enable row level security;

drop policy if exists "comentarios_select_todos" on public.comentarios;
create policy "comentarios_select_todos"
on public.comentarios
for select
to anon, authenticated
using (true);

drop policy if exists "comentarios_insert_todos" on public.comentarios;
create policy "comentarios_insert_todos"
on public.comentarios
for insert
to anon, authenticated
with check (
  length(trim(username)) > 0
  and length(trim(texto)) > 0
);

-- =========================================================
-- TABELA: vip_config
-- Configuracoes de contato, mensagens e limite de previa.
-- =========================================================

create table if not exists public.vip_config (
  id bigint generated by default as identity primary key,
  ativo boolean not null default true,
  contato_nome text not null default 'Amanda',
  telegram_url text,
  whatsapp_url text,
  botao_contato_texto text not null default 'Chamar no WhatsApp',
  mensagem_video text not null default 'Entre em contato com {contato} para assinar o VIP e continuar assistindo.',
  mensagem_foto text not null default 'Para ver todas as fotos sem censura, assine o VIP com {contato}.',
  preview_segundos integer not null default 5,
  updated_at timestamptz not null default now()
);

alter table public.vip_config
add column if not exists ativo boolean not null default true;

alter table public.vip_config
add column if not exists contato_nome text not null default 'Amanda';

alter table public.vip_config
add column if not exists telegram_url text;

alter table public.vip_config
add column if not exists whatsapp_url text;

alter table public.vip_config
add column if not exists botao_contato_texto text not null default 'Chamar no WhatsApp';

alter table public.vip_config
add column if not exists mensagem_video text not null default 'Entre em contato com {contato} para assinar o VIP e continuar assistindo.';

alter table public.vip_config
add column if not exists mensagem_foto text not null default 'Para ver todas as fotos sem censura, assine o VIP com {contato}.';

alter table public.vip_config
add column if not exists preview_segundos integer not null default 5;

alter table public.vip_config
add column if not exists updated_at timestamptz not null default now();

alter table public.vip_config enable row level security;

drop policy if exists "vip_config_select_ativos" on public.vip_config;
create policy "vip_config_select_ativos"
on public.vip_config
for select
to anon, authenticated
using (ativo = true);

-- =========================================================
-- TABELA: vip_ofertas
-- Itens da janelinha flutuante de valores.
-- =========================================================

create table if not exists public.vip_ofertas (
  id bigint generated by default as identity primary key,
  ativo boolean not null default true,
  ordem integer not null default 0,
  categoria text not null default 'vip',
  titulo text not null,
  descricao text,
  valor text not null,
  destaque boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.vip_ofertas
add column if not exists ativo boolean not null default true;

alter table public.vip_ofertas
add column if not exists ordem integer not null default 0;

alter table public.vip_ofertas
add column if not exists categoria text not null default 'vip';

alter table public.vip_ofertas
add column if not exists titulo text;

alter table public.vip_ofertas
add column if not exists descricao text;

alter table public.vip_ofertas
add column if not exists valor text;

alter table public.vip_ofertas
add column if not exists destaque boolean not null default false;

alter table public.vip_ofertas
add column if not exists created_at timestamptz not null default now();

alter table public.vip_ofertas
add column if not exists updated_at timestamptz not null default now();

alter table public.vip_ofertas enable row level security;

drop policy if exists "vip_ofertas_select_ativas" on public.vip_ofertas;
create policy "vip_ofertas_select_ativas"
on public.vip_ofertas
for select
to anon, authenticated
using (ativo = true);

-- =========================================================
-- TABELA: fotos_previas
-- Fotos censuradas/previews usadas no usuario teste.
-- =========================================================

create table if not exists public.fotos_previas (
  id bigint generated by default as identity primary key,
  ativo boolean not null default true,
  ordem integer not null default 0,
  titulo text not null default 'Previa',
  imagem_url text not null,
  thumb_url text,
  created_at timestamptz not null default now()
);

alter table public.fotos_previas
add column if not exists ativo boolean not null default true;

alter table public.fotos_previas
add column if not exists ordem integer not null default 0;

alter table public.fotos_previas
add column if not exists titulo text not null default 'Previa';

alter table public.fotos_previas
add column if not exists imagem_url text;

alter table public.fotos_previas
add column if not exists thumb_url text;

alter table public.fotos_previas
add column if not exists created_at timestamptz not null default now();

alter table public.fotos_previas enable row level security;

drop policy if exists "fotos_previas_select_ativas" on public.fotos_previas;
create policy "fotos_previas_select_ativas"
on public.fotos_previas
for select
to anon, authenticated
using (ativo = true);

-- =========================================================
-- TABELA: analytics_eventos
-- Registra acessos, cliques e jornada dos usuarios no site.
-- =========================================================

create table if not exists public.analytics_eventos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  username text,
  plano text,
  sessao_id text,
  ip text,
  evento text not null,
  alvo_tipo text,
  alvo_titulo text,
  alvo_url text,
  pagina text,
  user_agent text,
  detalhes jsonb not null default '{}'::jsonb
);

alter table public.analytics_eventos
add column if not exists created_at timestamptz not null default now();

alter table public.analytics_eventos
add column if not exists username text;

alter table public.analytics_eventos
add column if not exists plano text;

alter table public.analytics_eventos
add column if not exists sessao_id text;

alter table public.analytics_eventos
add column if not exists ip text;

alter table public.analytics_eventos
add column if not exists evento text;

alter table public.analytics_eventos
add column if not exists alvo_tipo text;

alter table public.analytics_eventos
add column if not exists alvo_titulo text;

alter table public.analytics_eventos
add column if not exists alvo_url text;

alter table public.analytics_eventos
add column if not exists pagina text;

alter table public.analytics_eventos
add column if not exists user_agent text;

alter table public.analytics_eventos
add column if not exists detalhes jsonb not null default '{}'::jsonb;

alter table public.analytics_eventos enable row level security;

drop policy if exists "analytics_insert_todos" on public.analytics_eventos;
create policy "analytics_insert_todos"
on public.analytics_eventos
for insert
to anon, authenticated
with check (
  evento is not null
  and length(trim(evento)) > 0
);

drop policy if exists "analytics_select_todos" on public.analytics_eventos;
create policy "analytics_select_todos"
on public.analytics_eventos
for select
to anon, authenticated
using (true);

-- =========================================================
-- TABELAS: sala virtual e chat de chamada previa
-- Cada atendimento fica separado por chamada_id, com mensagens salvas.
-- =========================================================

create table if not exists public.chamadas_previas (
  id uuid primary key default gen_random_uuid(),
  username text,
  plano text,
  sessao_id text,
  ip text,
  status text not null default 'aguardando',
  meet_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  liberado_em timestamptz,
  entrou_em timestamptz,
  finalizado_em timestamptz
);

alter table public.chamadas_previas
add column if not exists username text;

alter table public.chamadas_previas
add column if not exists plano text;

alter table public.chamadas_previas
add column if not exists sessao_id text;

alter table public.chamadas_previas
add column if not exists ip text;

alter table public.chamadas_previas
add column if not exists status text not null default 'aguardando';

alter table public.chamadas_previas
add column if not exists meet_url text;

alter table public.chamadas_previas
add column if not exists created_at timestamptz not null default now();

alter table public.chamadas_previas
add column if not exists updated_at timestamptz not null default now();

alter table public.chamadas_previas
add column if not exists liberado_em timestamptz;

alter table public.chamadas_previas
add column if not exists entrou_em timestamptz;

alter table public.chamadas_previas
add column if not exists finalizado_em timestamptz;

alter table public.chamadas_previas enable row level security;

drop policy if exists "chamadas_previas_select" on public.chamadas_previas;
create policy "chamadas_previas_select"
on public.chamadas_previas
for select
to anon, authenticated
using (true);

drop policy if exists "chamadas_previas_insert" on public.chamadas_previas;
create policy "chamadas_previas_insert"
on public.chamadas_previas
for insert
to anon, authenticated
with check (true);

drop policy if exists "chamadas_previas_update" on public.chamadas_previas;
create policy "chamadas_previas_update"
on public.chamadas_previas
for update
to anon, authenticated
using (true)
with check (true);

create table if not exists public.chamada_mensagens (
  id uuid primary key default gen_random_uuid(),
  chamada_id uuid not null references public.chamadas_previas(id) on delete cascade,
  autor_tipo text not null default 'usuario',
  autor_nome text,
  texto text not null,
  created_at timestamptz not null default now()
);

alter table public.chamada_mensagens
add column if not exists chamada_id uuid references public.chamadas_previas(id) on delete cascade;

alter table public.chamada_mensagens
add column if not exists autor_tipo text not null default 'usuario';

alter table public.chamada_mensagens
add column if not exists autor_nome text;

alter table public.chamada_mensagens
add column if not exists texto text not null default '';

alter table public.chamada_mensagens
add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'chamada_mensagens_autor_tipo_check'
      and conrelid = 'public.chamada_mensagens'::regclass
  ) then
    alter table public.chamada_mensagens
      add constraint chamada_mensagens_autor_tipo_check
      check (autor_tipo in ('usuario', 'admin', 'sistema'));
  end if;
end $$;

alter table public.chamada_mensagens enable row level security;

drop policy if exists "chamada_mensagens_select" on public.chamada_mensagens;
create policy "chamada_mensagens_select"
on public.chamada_mensagens
for select
to anon, authenticated
using (true);

drop policy if exists "chamada_mensagens_insert" on public.chamada_mensagens;
create policy "chamada_mensagens_insert"
on public.chamada_mensagens
for insert
to anon, authenticated
with check (true);

drop policy if exists "chamada_mensagens_update" on public.chamada_mensagens;
create policy "chamada_mensagens_update"
on public.chamada_mensagens
for update
to anon, authenticated
using (true)
with check (true);

create table if not exists public.sala_status (
  chave text primary key,
  online boolean not null default false,
  heartbeat_em timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.sala_status
add column if not exists online boolean not null default false;

alter table public.sala_status
add column if not exists heartbeat_em timestamptz;

alter table public.sala_status
add column if not exists updated_at timestamptz not null default now();

alter table public.sala_status enable row level security;

drop policy if exists "sala_status_select" on public.sala_status;
create policy "sala_status_select"
on public.sala_status
for select
to anon, authenticated
using (true);

drop policy if exists "sala_status_insert" on public.sala_status;
create policy "sala_status_insert"
on public.sala_status
for insert
to anon, authenticated
with check (true);

drop policy if exists "sala_status_update" on public.sala_status;
create policy "sala_status_update"
on public.sala_status
for update
to anon, authenticated
using (true)
with check (true);

-- =========================================================
-- FUNCOES: expiracao de VIP
-- =========================================================

create or replace function public.bloquear_usuarios_expirados()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.usuarios
  set
    ativo = false,
    atualizado_em = now()
  where ativo = true
    and expira_em is not null
    and expira_em <= now();
end;
$$;

grant execute on function public.bloquear_usuarios_expirados() to anon, authenticated;

create or replace function public.criar_ou_renovar_usuario(
  p_username text,
  p_senha text,
  p_plano text,
  p_dias integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.usuarios
  set
    senha = p_senha,
    ativo = true,
    plano = p_plano,
    expira_em = now() + make_interval(days => p_dias),
    atualizado_em = now()
  where username = p_username;

  if not found then
    insert into public.usuarios (
      username,
      senha,
      ativo,
      plano,
      expira_em,
      criado_em,
      atualizado_em
    )
    values (
      p_username,
      p_senha,
      true,
      p_plano,
      now() + make_interval(days => p_dias),
      now(),
      now()
    );
  end if;
end;
$$;

-- Esta funcao e para voce usar no SQL Editor.
-- Nao fica liberada para visitantes anonimos do site.
revoke execute on function public.criar_ou_renovar_usuario(text, text, text, integer) from public;

-- =========================================================
-- DADOS INICIAIS
-- =========================================================

insert into public.vip_config (
  ativo,
  contato_nome,
  telegram_url,
  whatsapp_url,
  botao_contato_texto,
  mensagem_video,
  mensagem_foto,
  preview_segundos
)
select
  true,
  'Amanda',
  '',
  '',
  'Chamar no WhatsApp',
  'Entre em contato com {contato} para assinar o VIP e continuar assistindo.',
  'Para ver todas as fotos sem censura, assine o VIP com {contato}.',
  5
where not exists (
  select 1 from public.vip_config
);

update public.vip_config
set
  preview_segundos = 5,
  botao_contato_texto = 'Chamar no WhatsApp'
where ativo = true
  and (
    preview_segundos is null
    or preview_segundos > 5
    or botao_contato_texto is null
    or botao_contato_texto = ''
    or botao_contato_texto ilike '%telegram%'
  );

insert into public.vip_ofertas (
  ordem,
  categoria,
  titulo,
  descricao,
  valor,
  destaque
)
select *
from (
  values
    (1, 'chamada', 'CHAMADA ATE GOZAR', 'MAXIMO 10mn', 'R$ 30,00', true),
    (2, 'chamada', 'CHAMADA 5 MINUTOS', null, 'R$ 20,00', false),
    (3, 'vip', '1 DIA DE ACESSO', null, 'R$ 10,00', false),
    (4, 'vip', 'SEMANAL 7 DIAS + VIP', null, 'R$ 15,00', true),
    (5, 'vip', 'MENSAL 30 DIAS + PREMIUM', null, 'R$ 20,00', true),
    (6, 'vip', '3 MESES DE ACESSO', null, 'R$ 50,00', false),
    (7, 'mimo', 'MANDA UM MIMO', 'Em troca de uma foto minha', 'R$ 5,00', false),
    (8, 'mimo', 'MANDA UM MIMO', 'Em troca de um video meu', 'R$ 10,00', false)
) as ofertas(ordem, categoria, titulo, descricao, valor, destaque)
where not exists (
  select 1 from public.vip_ofertas
);

insert into public.usuarios (
  username,
  senha,
  ativo,
  plano,
  expira_em
)
values (
  'teste',
  '123',
  true,
  'teste',
  null
)
on conflict (username) do update
set
  senha = excluded.senha,
  ativo = true,
  plano = 'teste',
  expira_em = null,
  atualizado_em = now();

insert into public.usuarios (
  username,
  senha,
  ativo,
  plano,
  expira_em
)
values (
  '123',
  '123',
  true,
  'teste',
  null
)
on conflict (username) do update
set
  senha = excluded.senha,
  ativo = true,
  plano = 'teste',
  expira_em = null,
  atualizado_em = now();

insert into public.usuarios (
  username,
  senha,
  ativo,
  plano,
  expira_em
)
values (
  'admin',
  'admin123',
  true,
  'admin',
  null
)
on conflict (username) do update
set
  senha = excluded.senha,
  ativo = true,
  plano = 'admin',
  expira_em = null,
  atualizado_em = now();

-- =========================================================
-- INDICES
-- =========================================================

create index if not exists conteudo_tipo_created_idx
on public.conteudo (tipo, created_at desc);

create index if not exists comentarios_created_idx
on public.comentarios (created_at desc);

create index if not exists fotos_previas_ordem_idx
on public.fotos_previas (ativo, ordem);

create index if not exists vip_ofertas_ordem_idx
on public.vip_ofertas (ativo, ordem);

create index if not exists usuarios_expira_idx
on public.usuarios (ativo, expira_em);

create index if not exists analytics_eventos_created_idx
on public.analytics_eventos (created_at desc);

create index if not exists analytics_eventos_plano_evento_idx
on public.analytics_eventos (plano, evento, created_at desc);

create index if not exists analytics_eventos_ip_idx
on public.analytics_eventos (ip, created_at desc);

create index if not exists analytics_eventos_sessao_idx
on public.analytics_eventos (sessao_id, created_at desc);

create index if not exists chamadas_previas_ip_sessao_status_idx
on public.chamadas_previas (ip, sessao_id, status, created_at);

create index if not exists chamadas_previas_status_created_idx
on public.chamadas_previas (status, created_at);

create index if not exists chamada_mensagens_chamada_created_idx
on public.chamada_mensagens (chamada_id, created_at);

-- =========================================================
-- COMANDOS UTEIS
-- =========================================================

-- Criar/renovar usuario por 1 dia:
-- select public.criar_ou_renovar_usuario('cliente1', 'senha123', '1_dia', 1);

-- Criar/renovar usuario por 7 dias:
-- select public.criar_ou_renovar_usuario('cliente1', 'senha123', '7_dias', 7);

-- Criar/renovar usuario por 30 dias:
-- select public.criar_ou_renovar_usuario('cliente1', 'senha123', '30_dias', 30);

-- Criar/renovar usuario por 3 meses:
-- select public.criar_ou_renovar_usuario('cliente1', 'senha123', '3_meses', 90);

-- Ver usuarios:
-- select username, plano, ativo, expira_em, expira_em at time zone 'America/Sao_Paulo' as expira_no_brasil
-- from public.usuarios
-- order by expira_em nulls last;

-- Inserir video:
-- insert into public.conteudo (tipo, titulo, stream_url, thumb_url)
-- values ('video', 'Video 1', 'https://pub-seu-bucket.r2.dev/video.mp4', null);

-- Inserir foto VIP:
-- insert into public.conteudo (tipo, titulo, stream_url, thumb_url)
-- values ('foto', 'Foto 1', 'https://pub-seu-bucket.r2.dev/foto.jpg', null);

-- Inserir foto de previa para usuario teste:
-- insert into public.fotos_previas (titulo, imagem_url, ordem)
-- values ('Previa 1', 'https://pub-seu-bucket.r2.dev/foto-censurada.jpg', 1);

-- Ver resumo de acessos:
-- select plano, evento, count(*) as total
-- from public.analytics_eventos
-- group by plano, evento
-- order by total desc;

-- Ver jornada de um IP:
-- select created_at at time zone 'America/Sao_Paulo' as horario_brasil, username, plano, evento, alvo_titulo
-- from public.analytics_eventos
-- where ip = 'COLOQUE_O_IP_AQUI'
-- order by created_at asc;
