-- Modo de previa para o usuario teste / 123.
-- Rode este arquivo no SQL Editor do Supabase.

create table if not exists public.vip_config (
  id bigint generated by default as identity primary key,
  ativo boolean not null default true,
  contato_nome text not null default 'Amanda',
  telegram_url text,
  whatsapp_url text,
  botao_contato_texto text not null default 'Chamar no WhatsApp',
  mensagem_video text not null default 'Entre em contato com {contato} para assinar o VIP e continuar assistindo.',
  mensagem_foto text not null default 'Para ver todas as fotos sem censura, assine o VIP com {contato}.',
  preview_segundos integer not null default 5,
  updated_at timestamptz not null default now()
);

create table if not exists public.fotos_previas (
  id bigint generated by default as identity primary key,
  ativo boolean not null default true,
  ordem integer not null default 0,
  titulo text not null default 'Previa',
  imagem_url text not null,
  thumb_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.vip_ofertas (
  id bigint generated by default as identity primary key,
  ativo boolean not null default true,
  ordem integer not null default 0,
  categoria text not null default 'vip',
  titulo text not null,
  descricao text,
  valor text not null,
  destaque boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.vip_config enable row level security;
alter table public.fotos_previas enable row level security;
alter table public.vip_ofertas enable row level security;

alter table public.vip_config
add column if not exists whatsapp_url text;

alter table public.vip_config
add column if not exists botao_contato_texto text not null default 'Chamar no WhatsApp';

drop policy if exists "vip_config_select_ativos" on public.vip_config;
create policy "vip_config_select_ativos"
on public.vip_config
for select
to anon, authenticated
using (ativo = true);

drop policy if exists "fotos_previas_select_ativas" on public.fotos_previas;
create policy "fotos_previas_select_ativas"
on public.fotos_previas
for select
to anon, authenticated
using (ativo = true);

drop policy if exists "vip_ofertas_select_ativas" on public.vip_ofertas;
create policy "vip_ofertas_select_ativas"
on public.vip_ofertas
for select
to anon, authenticated
using (ativo = true);

insert into public.vip_config (
  ativo,
  contato_nome,
  telegram_url,
  whatsapp_url,
  botao_contato_texto,
  mensagem_video,
  mensagem_foto,
  preview_segundos
)
select
  true,
  'Amanda',
  '',
  '',
  'Chamar no WhatsApp',
  'Entre em contato com {contato} para assinar o VIP e continuar assistindo.',
  'Para ver todas as fotos sem censura, assine o VIP com {contato}.',
  5
where not exists (
  select 1 from public.vip_config
);

update public.vip_config
set preview_segundos = 5
where ativo = true
  and preview_segundos > 5;

update public.vip_config
set botao_contato_texto = 'Chamar no WhatsApp'
where ativo = true
  and (
    botao_contato_texto is null
    or botao_contato_texto = ''
    or botao_contato_texto ilike '%telegram%'
  );

insert into public.vip_ofertas (
  ordem,
  categoria,
  titulo,
  descricao,
  valor,
  destaque
)
select *
from (
  values
    (1, 'chamada', 'CHAMADA ATE GOZAR ❤️', 'MAXIMO 10mn', 'R$ 30,00', true),
    (2, 'chamada', 'CHAMADA 5 MINUTOS ❤️', null, 'R$ 20,00', false),
    (3, 'vip', '1 DIA DE ACESSO', null, 'R$ 10,00', false),
    (4, 'vip', 'SEMANAL 7 DIAS + VIP 🎁', null, 'R$ 15,00', true),
    (5, 'vip', 'MENSAL 30 DIAS + PREMIUM 🎁', null, 'R$ 20,00', true),
    (6, 'vip', '3 MESES DE ACESSO 🎁', null, 'R$ 50,00', false),
    (7, 'mimo', 'MANDA UM MIMO 🎁', 'Em troca de uma foto minha', 'R$ 5,00', false),
    (8, 'mimo', 'MANDA UM MIMO 🎁', 'Em troca de um video meu', 'R$ 10,00', false)
) as ofertas(ordem, categoria, titulo, descricao, valor, destaque)
where not exists (
  select 1 from public.vip_ofertas
);

update public.usuarios
set senha = '123'
where username = 'teste';

insert into public.usuarios (username, senha)
select 'teste', '123'
where not exists (
  select 1 from public.usuarios where username = 'teste'
);

-- Para cadastrar uma foto censurada de previa:
-- Agora basta preencher imagem_url. thumb_url pode ficar vazio.
-- Use preferencialmente um link publico do Cloudflare R2.
-- insert into public.fotos_previas (titulo, imagem_url, ordem)
-- values ('Previa 1', 'https://pub-seu-bucket.r2.dev/foto-censurada.jpg', 1);

-- Para cadastrar um video no R2:
-- insert into public.conteudo (tipo, titulo, stream_url, thumb_url)
-- values ('video', 'Video 1', 'https://pub-seu-bucket.r2.dev/video.mp4', null);

-- Para trocar o WhatsApp do botao:
-- update public.vip_config
-- set whatsapp_url = 'https://wa.me/5599999999999',
--     botao_contato_texto = 'Chamar no WhatsApp',
--     contato_nome = 'Amanda'
-- where ativo = true;
